sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t ashutosh232120535331/frontend -f Dockerfile.dev .

script:
  - docker run -e CI=true ashutosh232120535331/frontend npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'DockerFrontendENV'
  env: 'Dockerfrontend-env1'
  bucket_name: 'elasticbeanstalk-us-east-1-459812524273'
  bucket_path: 'DockerFrontendENV'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
